version: "3"
services:
  
  ui:
   build:
      context: ./ui
      dockerfile: Dockerfile.dev
   ports:
    -  8080:8080
   container_name: mevn-ui
   networks:
    -  mevn-stack-net
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   depends_on:
    - api
   stdin_open: true
   tty: true

  api:
   image: node:latest
   ports:
     - 3080:3080
   container_name: mevn-api
   networks:
     - mevn-stack-net
   volumes:
    - ./api:/usr/app
   working_dir: "/usr/app"
   stdin_open: true
   tty: true
   command: bash
   depends_on:
    - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mevn-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mevn-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local